from core.db import pool

def get_estructura(cod):
    q = """SELECT
SR.CODIGO_REPARTICION,
SR.NOMBRE_REPARTICION,
(SELECT CODIGO_REPARTICION FROM TRACK_GED.SADE_REPARTICION WHERE ID_REPARTICION=SR.REP_PADRE) AS REP_PADRE,
(SELECT CODIGO_REPARTICION FROM TRACK_GED.SADE_REPARTICION WHERE ID_REPARTICION=SR.MINISTERIO) AS MINISTERIO,
LEVEL AS NIVEL,
SYS_CONNECT_BY_PATH(CODIGO_REPARTICION, '/') AS RUTA
FROM TRACK_GED.SADE_REPARTICION SR
WHERE SR.ESTADO_REGISTRO = 1 AND TRUNC(SR.VIGENCIA_HASTA) > TRUNC(SYSDATE)
START WITH SR.CODIGO_REPARTICION = :COD
CONNECT BY NOCYCLE PRIOR SR.ID_REPARTICION = SR.REP_PADRE
ORDER SIBLINGS BY CODIGO_REPARTICION ASC"""
    con = pool.acquire()
    cur = con.cursor()
    cur.execute(q, (cod,))
    datos = cur.fetchall()
    columnas = [x[0] for x in cur.description]
    resultado = [dict(zip(columnas, fila)) for fila in datos]
    pool.release(con)
    return resultado